//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaAutos.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VentasEntities : DbContext
    {
        public VentasEntities()
            : base("name=VentasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CEstadoArticulo> CEstadoArticulo { get; set; }
        public virtual DbSet<CMarcaVehiculo> CMarcaVehiculo { get; set; }
        public virtual DbSet<CPeriodoPago> CPeriodoPago { get; set; }
        public virtual DbSet<CTipoArticulo> CTipoArticulo { get; set; }
        public virtual DbSet<CTipoPago> CTipoPago { get; set; }
        public virtual DbSet<CTipoVehiculo> CTipoVehiculo { get; set; }
        public virtual DbSet<CTipoVenta> CTipoVenta { get; set; }
        public virtual DbSet<CTransmision> CTransmision { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TArticulo> TArticulo { get; set; }
        public virtual DbSet<TCliente> TCliente { get; set; }
        public virtual DbSet<TCompra> TCompra { get; set; }
        public virtual DbSet<TFinanciamiento> TFinanciamiento { get; set; }
        public virtual DbSet<TPagoFinanciamiento> TPagoFinanciamiento { get; set; }
        public virtual DbSet<TTelefonoCliente> TTelefonoCliente { get; set; }
        public virtual DbSet<TUsuario> TUsuario { get; set; }
        public virtual DbSet<TVehiculo> TVehiculo { get; set; }
        public virtual DbSet<TVenta> TVenta { get; set; }
    }
}
