//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaAutos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TArticulo
    {
        public int IdArticulo { get; set; }
        public string Descripcion { get; set; }
        public decimal Valor { get; set; }
        public int IdTipo { get; set; }
        public int IdEstado { get; set; }
        public Nullable<int> IdCliente { get; set; }
    }
}
