//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaAutos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCompra
    {
        public int IdCliente { get; set; }
        public string Placa { get; set; }
        public decimal Monto { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual TCliente TCliente { get; set; }
        public virtual TVehiculo TVehiculo { get; set; }
    }
}
