//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaAutos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TFinanciamiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TFinanciamiento()
        {
            this.TPagoFinanciamiento = new HashSet<TPagoFinanciamiento>();
        }
    
        public int IdFinanciamiento { get; set; }
        public short Interes { get; set; }
        public short Plazo { get; set; }
        public System.DateTime Monto { get; set; }
        public int IdPeriodoPago { get; set; }
        public Nullable<int> IdVenta { get; set; }
    
        public virtual CPeriodoPago CPeriodoPago { get; set; }
        public virtual TVenta TVenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TPagoFinanciamiento> TPagoFinanciamiento { get; set; }
    }
}
