//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaAutos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TFinanciamiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TFinanciamiento()
        {
            this.TPagoFinanciamiento = new HashSet<TPagoFinanciamiento>();
            this.TVenta = new HashSet<TVenta>();
        }
    
        public int IdFinanciamiento { get; set; }
        public short Interes { get; set; }
        public short Plazo { get; set; }
        public int IdPeriodoPago { get; set; }
        public string Descripcion { get; set; }
    
        public virtual CPeriodoPago CPeriodoPago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TPagoFinanciamiento> TPagoFinanciamiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TVenta> TVenta { get; set; }
    }
}
