//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaAutos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TFinanciamiento
    {
        public int IdFinanciamiento { get; set; }
        public short Interes { get; set; }
        public short Plazo { get; set; }
        public int IdPeriodoPago { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> IdVenta { get; set; }
    
        public virtual CPeriodoPago CPeriodoPago { get; set; }
        public virtual TVenta TVenta { get; set; }
    }
}
