//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaAutos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPagoFinanciamiento
    {
        public int IdPagoFinan { get; set; }
        public int IdVenta { get; set; }
        public int IdTipoPago { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public int IdFinanciamiento { get; set; }
        public Nullable<decimal> Intereses { get; set; }
    
        public virtual CTipoPago CTipoPago { get; set; }
        public virtual TFinanciamiento TFinanciamiento { get; set; }
    }
}
