//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaAutos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TVenta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TVenta()
        {
            this.TFinanciamiento = new HashSet<TFinanciamiento>();
            this.TPagoFinanciamiento = new HashSet<TPagoFinanciamiento>();
            this.TPagos = new HashSet<TPagos>();
        }
    
        public int IdVenta { get; set; }
        public decimal Monto { get; set; }
        public System.DateTime Fecha { get; set; }
        public int IdTipoVenta { get; set; }
        public int IdCliente { get; set; }
        public decimal Saldo { get; set; }
        public string Placa { get; set; }
        public Nullable<decimal> Interes { get; set; }
    
        public virtual CTipoVenta CTipoVenta { get; set; }
        public virtual TCliente TCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TFinanciamiento> TFinanciamiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TPagoFinanciamiento> TPagoFinanciamiento { get; set; }
        public virtual TVehiculo TVehiculo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TPagos> TPagos { get; set; }
    }
}
